import { test, expect } from '@playwright/test';
import { UiSmokePage } from "../pages/page";

test('ui-smoke', async ({ page }) => {
  page.setDefaultTimeout(30000);
  await page.goto("https://stg.gajab.com/", { waitUntil: 'domcontentloaded', timeout: 30000 });
  await page.locator('body').waitFor({ state: 'visible', timeout: 10000 });
  await page.waitForLoadState('domcontentloaded');
  await page.waitForTimeout(2000);
  await page.locator('#location-fullscreen-click-blocker').click({ force: true }).catch(() => {});
  await page.locator('#home-bargain-guide-portal-overlay').click({ force: true }).catch(() => {});
  const ui = new UiSmokePage(page);
  await page.goto("", { waitUntil: 'domcontentloaded' });
  await page.goto("https://stg.gajab.com/", { waitUntil: 'domcontentloaded' });
  await expect(page.getByText("home page is visible", { exact: false })).toBeVisible();
  await ui.click("header_login_btn");
  await expect(page).toHaveURL(new RegExp("signin"));
  await page.getByText("Request OTP", { exact: false }).first().click();
  await page.getByText("Male", { exact: false }).first().click();
  await page.getByText("Submit", { exact: false }).first().click();
  await ui.hover("location_desktop_menu_btn");
  await ui.hover("location_desktop_menu_btn");
  await ui.fill("location_desktop_search_input", "560001");
  await expect(page.getByText("Bengaluru, Karnataka 560001, India", { exact: false })).toBeVisible();
  await page.getByText("Bengaluru, Karnataka 560001, India", { exact: false }).first().click();
  await expect(page.getByText("gajab deal of the day section is visible", { exact: false })).toBeVisible();
  await expect(page.getByText("Gajab Deal of the Day", { exact: false })).toBeVisible();
  await expect(page.getByText("Gajab Deal of the Day", { exact: false })).toBeVisible();
  await expect(page.getByText("Gajab Deal of the Day", { exact: false })).toBeVisible();
  await ui.click("home_wp2_view_more");
  await ui.click("home_wp2_view_more");
  await expect(page.getByText("just bargained section is visible on home page", { exact: false })).toBeVisible();
  await expect(page.getByText("Just Bargained", { exact: false })).toBeVisible();
  await page.getByText("Toys & Games", { exact: false }).first().click();
  await page.getByText("More", { exact: false }).first().click();
  await page.getByText("SERA'S BASKET", { exact: false }).first().click();
  await page.locator('#price-filter-website-min-range-input').fill("427");
  await page.locator('#price-filter-website-max-range-input').fill("727");
  await page.getByText("the selected product", { exact: false }).first().click();
  await page.getByText("bargain button to start bargaining", { exact: false }).first().click();
  await page.getByText("accept button to accept the final bargain offer", { exact: false }).first().click();
  await page.getByText("Buy Now", { exact: false }).first().click();
  await page.getByText("Home Address Type", { exact: false }).first().click();
  await page.getByText("Save Address", { exact: false }).first().click();
  await ui.click("checkout_payment_online_option");
  await page.getByText("Pay", { exact: false }).first().click();
  await page.getByText("pay button", { exact: false }).first().click();
  await page.locator('#checkout-payment-online-option').first().click({ force: true }).catch(() => {});
  const payNow = page.locator('#checkout-pay-now-mobile-btn, #checkout-pay-now-desktop-btn').first();
  await payNow.click({ force: true });
  await page.waitForTimeout(1500);
  const razorFrame = page.frames().find((f) => /razorpay\.com\/v1\/checkout/i.test(f.url()));
  if (!razorFrame) throw new Error('Razorpay frame not found');
  const mobileInput = razorFrame.getByRole('textbox', { name: /mobile number/i }).first();
  if (await mobileInput.count()) {
    await mobileInput.fill('9876543210');
    const continueBtn = razorFrame.getByRole('button', { name: /^continue$/i }).first();
    if (await continueBtn.count()) await continueBtn.click();
    await page.waitForTimeout(1000);
  }
  const netBanking = razorFrame.getByText('Netbanking', { exact: false }).first();
  await netBanking.click();
  await expect(page.locator('body')).toBeVisible();
});
